<?php
const DIR_APP = __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR;
const DIR_PUBLIC = __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR;
const DIR_TEMPLATES = DIR_APP . 'Templates' . DIRECTORY_SEPARATOR;
const DIR_LAYOUTS = DIR_TEMPLATES . 'Layouts' . DIRECTORY_SEPARATOR;